////------------------------------------------------------------------------------
//// <auto-generated>
////    This code was generated from a template.
////
////    Manual changes to this file may cause unexpected behavior in your application.
////    Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------
//
//using System;
//using System.Data.Objects;
//using System.Data.Objects.DataClasses;
//using System.Data.EntityClient;
//using System.ComponentModel;
//using System.Xml.Serialization;
//using System.Runtime.Serialization;
//
//[assembly: EdmSchemaAttribute()]
//
//namespace CommonTypes.Database
//{
//    #region Contexts
//    
//    /// <summary>
//    /// No Metadata Documentation available.
//    /// </summary>
//    public partial class ExampleDataEntities : ObjectContext
//    {
//        #region Constructors
//    
//        /// <summary>
//        /// Initializes a new ExampleDataEntities object using the connection string found in the 'ExampleDataEntities' section of the application configuration file.
//        /// </summary>
//        public ExampleDataEntities() : base("name=ExampleDataEntities", "ExampleDataEntities")
//        {
//            this.ContextOptions.LazyLoadingEnabled = true;
//            OnContextCreated();
//        }
//    
//        /// <summary>
//        /// Initialize a new ExampleDataEntities object.
//        /// </summary>
//        public ExampleDataEntities(string connectionString) : base(connectionString, "ExampleDataEntities")
//        {
//            this.ContextOptions.LazyLoadingEnabled = true;
//            OnContextCreated();
//        }
//    
//        /// <summary>
//        /// Initialize a new ExampleDataEntities object.
//        /// </summary>
//        public ExampleDataEntities(EntityConnection connection) : base(connection, "ExampleDataEntities")
//        {
//            this.ContextOptions.LazyLoadingEnabled = true;
//            OnContextCreated();
//        }
//    
//        #endregion
//    
//        #region Partial Methods
//    
//        partial void OnContextCreated();
//    
//        #endregion
//    
//        #region ObjectSet Properties
//    
//        /// <summary>
//        /// No Metadata Documentation available.
//        /// </summary>
//        public ObjectSet<Person> Persons
//        {
//            get
//            {
//                if ((_Persons == null))
//                {
//                    _Persons = base.CreateObjectSet<Person>("Persons");
//                }
//                return _Persons;
//            }
//        }
//        private ObjectSet<Person> _Persons;
//
//        #endregion
//        #region AddTo Methods
//    
//        /// <summary>
//        /// Deprecated Method for adding a new object to the Persons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
//        /// </summary>
//        public void AddToPersons(Person person)
//        {
//            base.AddObject("Persons", person);
//        }
//
//        #endregion
//    }
//    
//
//    #endregion
//    
//    #region Entities
//    
//    /// <summary>
//    /// No Metadata Documentation available.
//    /// </summary>
//    [EdmEntityTypeAttribute(NamespaceName="ExampleDataModel", Name="Person")]
//    [Serializable()]
//    [DataContractAttribute(IsReference=true)]
//    public partial class Person : EntityObject
//    {
//        #region Factory Method
//    
//        /// <summary>
//        /// Create a new Person object.
//        /// </summary>
//        /// <param name="age">Initial value of the Age property.</param>
//        /// <param name="id">Initial value of the Id property.</param>
//        public static Person CreatePerson(global::System.Int32 age, global::System.Int32 id)
//        {
//            Person person = new Person();
//            person.Age = age;
//            person.Id = id;
//            return person;
//        }
//
//        #endregion
//        #region Primitive Properties
//    
//        /// <summary>
//        /// No Metadata Documentation available.
//        /// </summary>
//        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
//        [DataMemberAttribute()]
//        public global::System.String State
//        {
//            get
//            {
//                return _State;
//            }
//            set
//            {
//                OnStateChanging(value);
//                ReportPropertyChanging("State");
//                _State = StructuralObject.SetValidValue(value, true);
//                ReportPropertyChanged("State");
//                OnStateChanged();
//            }
//        }
//        private global::System.String _State;
//        partial void OnStateChanging(global::System.String value);
//        partial void OnStateChanged();
//    
//        /// <summary>
//        /// No Metadata Documentation available.
//        /// </summary>
//        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
//        [DataMemberAttribute()]
//        public global::System.String Name
//        {
//            get
//            {
//                return _Name;
//            }
//            set
//            {
//                OnNameChanging(value);
//                ReportPropertyChanging("Name");
//                _Name = StructuralObject.SetValidValue(value, true);
//                ReportPropertyChanged("Name");
//                OnNameChanged();
//            }
//        }
//        private global::System.String _Name;
//        partial void OnNameChanging(global::System.String value);
//        partial void OnNameChanged();
//    
//        /// <summary>
//        /// No Metadata Documentation available.
//        /// </summary>
//        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
//        [DataMemberAttribute()]
//        public global::System.String Company
//        {
//            get
//            {
//                return _Company;
//            }
//            set
//            {
//                OnCompanyChanging(value);
//                ReportPropertyChanging("Company");
//                _Company = StructuralObject.SetValidValue(value, true);
//                ReportPropertyChanged("Company");
//                OnCompanyChanged();
//            }
//        }
//        private global::System.String _Company;
//        partial void OnCompanyChanging(global::System.String value);
//        partial void OnCompanyChanged();
//    
//        /// <summary>
//        /// No Metadata Documentation available.
//        /// </summary>
//        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
//        [DataMemberAttribute()]
//        public global::System.Int32 Age
//        {
//            get
//            {
//                return _Age;
//            }
//            set
//            {
//                OnAgeChanging(value);
//                ReportPropertyChanging("Age");
//                _Age = StructuralObject.SetValidValue(value);
//                ReportPropertyChanged("Age");
//                OnAgeChanged();
//            }
//        }
//        private global::System.Int32 _Age;
//        partial void OnAgeChanging(global::System.Int32 value);
//        partial void OnAgeChanged();
//    
//        /// <summary>
//        /// No Metadata Documentation available.
//        /// </summary>
//        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
//        [DataMemberAttribute()]
//        public global::System.Int32 Id
//        {
//            get
//            {
//                return _Id;
//            }
//            set
//            {
//                if (_Id != value)
//                {
//                    OnIdChanging(value);
//                    ReportPropertyChanging("Id");
//                    _Id = StructuralObject.SetValidValue(value);
//                    ReportPropertyChanged("Id");
//                    OnIdChanged();
//                }
//            }
//        }
//        private global::System.Int32 _Id;
//        partial void OnIdChanging(global::System.Int32 value);
//        partial void OnIdChanged();
//
//        #endregion
//    
//    }
//
//    #endregion
//    
//}
